# may also need to set each with `mise use -g {TOOL}@lastest`
[tools]

# languages / runtimes
node = "latest"
deno = "latest"
java = "latest"
python = "latest"
ruby = "latest"
go = "latest"

# package / project managers
uv = "latest"
pnpm = "latest"

# engines
bun = "latest"

# system tools installed globally below to avoid project-level runtime-version collisions:

# open source coding agent
"npm:@mariozechner/pi-coding-agent" = "latest"
# OpenAI coding agent
"aqua:openai/codex" = "latest"

[settings]

# config files with these prefixes will be trusted by default
trusted_config_paths = [
    '~/dev',
]
