# may also need to set each with `mise use -g {TOOL}@lastest`
[tools]

node = "latest"
deno = "latest"
java = "latest"
python = "latest"
ruby = "latest"
go = "latest"

# package / project managers
uv = "latest"
pnpm = "latest"

# engines
bun = "latest"

[settings]

# config files with these prefixes will be trusted by default
trusted_config_paths = [
    '~/dev',
]
