# map prefix keys
unbind C-b
set-option -g prefix C-_      # Ctrl+/
set-option -g prefix2 M-z     # Alt+z
bind-key C-_ send-prefix
bind-key M-z send-prefix -2

# allow mouse scrolling
set -g mouse on

# window renumbering & index 1 for predictable keyboard mgmt
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1


# list of plugins
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "sainnhe/tmux-fzf"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "semi710/minimal-tmux-status"


# Initialize tpack (keep this line at the very bottom of tmux.conf)
run "tpack init"
set -g @plugin "alexwforsythe/tmux-which-key"
